name: mara-db

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Chechout code
        uses: actions/checkout@v6.0.2
      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install DuckDB CLI
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.5.1/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          sudo mv duckdb /usr/local/bin/duckdb
          duckdb --version
      - name: Install application
        env:
          pythonversion: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          pip install .[test]
          echo Finished successful build with Python $pythonversion
      - name: Test with pytest
        run: |
          make tests/local_config.py
          pytest -v tests
